### The goal here is to visualize a little the masked segmentation in order to better undestand when the heartbeat starts/stops

In [2]:
import h5py
import numpy as np
import matplotlib.pyplot as plt 
import os

In [4]:
data_rw = h5py.File('/usr/bmicnas02/data-biwi-01/jeremy_students/data/inselspital/kady/hand_segmented_centerlines/patients_compressed_sensing_masked_sliced_images.hdf5')
print(data_rw.keys()  )

#data_cnn = h5py.File('/usr/bmicnas02/data-biwi-01/jeremy_students/lschlyter/CNN-segmentation/logdir/inference_results/unet3d_da_0.0nchannels4_r1_loss_dice_cut_z_False_full_run_only_w_labels_e80_lr_1e-3_AdamW_val_40/train_masked_sliced_images_full_aorta.hdf5')
#data_cnn.keys()  

<KeysViewHDF5 ['sliced_images_patients']>


In [9]:
slices_rw = data_rw['sliced_images_patients']
slices_rw_np = slices_rw[:]
patient_slices_rw_np = slices_rw_np.reshape(-1, 64, 32,32,48,4)
print(patient_slices_rw_np.shape)

mean_patient_rw = abs(patient_slices_rw_np[:,:,:,:,:,1]).mean(axis=(1,2,3))
mean_patient_rw.argmax(axis=1)


(8, 64, 32, 32, 48, 4)


array([2, 1, 2, 2, 3, 2, 4, 2])

In [ ]:
slices_cnn = data_cnn['sliced_images_train']
slices_cnn_np = slices_cnn[:]
patient_slices_cnn_np = slices_cnn_np.reshape(28, -1, 32,32,48,4)
patient_slices_cnn_np.shape
mean_patient_cnn = abs(patient_slices_cnn_np[:,:,:,:,:,1]).mean(axis=(1,2,3))
mean_patient_cnn.argmax(axis=1)


In [114]:
, mean_patient_cnn.argmax(axis=1)

(array([3, 3, 3, 2, 4, 4, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4,
        4, 4, 3, 4, 4]),
 array([4, 4, 5, 4, 4, 5, 5, 3, 4, 4, 3, 5, 4, 4, 4, 4, 4, 4, 4, 5, 3, 4,
        3, 6, 4, 4, 5, 4]))